### ISSUE TITLE
Cannot find module 'tough-cookie'

### ISSUE THREAD

**Issue by ERmilburn02** [Inrixia/floatplaneAPI.ts#1]
Attempting to install the npm package and then running the sample code from the usage section gives the following error:
```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'tough-cookie'
Require stack:
- C:\Users\ERmil\tmp\fp\node_modules\floatplane\index.js
- C:\Users\ERmil\tmp\fp\index.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:952:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:88:18)←[39m
    at Object.<anonymous> (C:\Users\ERmil\tmp\fp\node_modules\←[4mfloatplane←[24m\index.js:8:24)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:952:19)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'C:\\Users\\ERmil\\tmp\\fp\\node_modules\\floatplane\\index.js'←[39m,
    ←[32m'C:\\Users\\ERmil\\tmp\\fp\\index.js'←[39m
  ]
}
```

**Comment by Inrixia** [comment]
Thankyou, seems that a required dependency was set as only needed for dev and not being installed. This was fixed in https://github.com/Inrixia/floatplaneAPI.ts/commit/77961ae755861c5808282f7d5a69d6ca11919767

I have also updated the example code to use a TS example and the exports to not use default so that its a bit nicer to use with normal JS if you aren't using TS.

Should all be fixed now.
